### ISSUE TITLE
user story: options to vote

### ISSUE THREAD

**Issue by Maya-Claveau** [Maya-Claveau/My-First-Agile-Project#3]
In order to **have options** as a **voter**, I can **choose to add a comment**

**Comment by Maya-Claveau** [comment]
As a **voter**, I can choose to **vote anonymously** to **hide my identity if i wish to**

## Acceptance Criteria
* Acceptance Criteria 1: there should be a button appear before the submit button
* Acceptance Criteria 2: the button should be a checkbox

## Tasks
- [ ] Task 1: add vote anonymously button on the page
- [ ] Task 2: design the button for different devices
- [ ] Task 3: style the button that match the page style
