### ISSUE TITLE
user story: as a admin i can add votes

### ISSUE THREAD

**Issue by Maya-Claveau** [Maya-Claveau/My-First-Agile-Project#4]
In order to **maintain a full record** as a **Administrator**, I can **add votes and keep record of all voting details**

## Acceptance Criteria
* Acceptance Critieria 1: there should be a add vote button for the admin
* Acceptance Critieria 2: there should be a button for viewing all the votes
* Acceptance Critieria 3: 

## Tasks
- [ ] Task 1: add the add vote button to the page for admin
- [ ] Task 2: design the button for different devices
- [ ] Task 3: style the button to match the page
- [ ] Task 4: add the view votes button
- [ ] Task 5: design the view button for different devices
- [ ] Task 6: style the button to match the page
